name: Test README.md Examples
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci-examples.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-examples.yml

# NOTE: These environment variables are NOT considered part of the examples.
# They are only used to help cut down on building and pushing duplicate images.
env:
  PUSH: ${{ vars.EXAMPLES_PUSH || 'never' }}
  REGISTRY: ${{ vars.EXAMPLES_REGISTRY || 'ghcr.io' }}

jobs:
  quick-start:
    name: Publish a Prebuilt Dev Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Prebuild Environment
        uses: cennis91/setup-prebuild-env@v1
        with:
          registry: ${{ env.REGISTRY || 'ghcr.io' }}

      - name: Prebuild and Publish Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY || 'ghcr.io' }}/${{ github.repository }}/quick-start
          push: ${{ env.PUSH || 'always' }}

  multi-platform:
    name: Publish a Prebuilt Multi-Platform Dev Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Prebuild Environment
        id: setup
        uses: cennis91/setup-prebuild-env@v1
        with:
          platforms: linux/amd64,linux/arm64
          registry: ${{ env.REGISTRY || 'ghcr.io' }}

      - name: Prebuild and Publish Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY || 'ghcr.io' }}/${{ github.repository }}/multi-platform
          push: ${{ env.PUSH || 'always' }}
          platform: ${{ steps.setup.outputs.platforms }}

  custom-steps:
    name: Publish a Prebuilt Dev Container Image with Custom Steps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Prebuild Environment
        id: setup
        uses: cennis91/setup-prebuild-env@v1
        with:
          platforms: linux/amd64,linux/arm64
          registry: ${{ env.REGISTRY || 'ghcr.io' }}
          setup-buildx: false
          setup-qemu: false

      - name: Setup QEMU (Manually without cache)
        uses: docker/setup-qemu-action@v3
        with:
          cache-image: false
          platforms: ${{ steps.setup.outputs.platforms }}

      - name: Setup Buildx (Manually with debug)
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          platforms: ${{ steps.setup.outputs.platforms }}

      - name: Prebuild and Publish Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY || 'ghcr.io' }}/${{ github.repository }}/custom-steps
          push: ${{ env.PUSH || 'always' }}
          platform: ${{ steps.setup.outputs.platforms }}
