name: Lint Repository
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args:
            -color

  examples:
    name: Check README.md Examples
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          - quick-start
          - multi-platform
          - custom-steps

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Example ${{ matrix.example }}
        env:
          ACTUAL_FILE: README.md
          EXPECTED_FILE: .github/workflows/ci-examples.yml
          JOB_NAME: ${{ matrix.example }}
        run: |
          printf "::group::%s\n" "Check Example $JOB_NAME"
          ./.github/scripts/check-readme-example.sh "$ACTUAL_FILE" "$EXPECTED_FILE" "$JOB_NAME"
          printf "::endgroup::\n"

  golang:
    name: Check Golang Constants
    runs-on: ubuntu-latest

    strategy:
      matrix:
        constant:
          - KNOWN_ARCH
          - KNOWN_OS

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compare Constant ${{ matrix.constant }}
        env:
          CONSTANT: ${{ matrix.constant }}
        run: |
          printf "::group::%s\n" "Compare Constant $CONSTANT"
          ./.github/scripts/check-golang-constant.sh "$CONSTANT"
          printf "::endgroup::\n"

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s sh -P src
