name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      platforms:
        description: The OCI platforms to build for
        required: false
      repository:
        description: The image repository to publish to
        required: false
      runs-on:
        description: The type of machine to run the workflow on
        required: false
        default: ubuntu-latest
      registry:
        description: The container registry to publish to
        required: false
      tag:
        description: The Docker image tag to publish
        required: false

env:
  DEFAULT_PLATFORMS: linux/amd64,linux/arm64
  DEFAULT_REGISTRY: ghcr.io
  DEFAULT_REPOSITORY: ${{ github.repository }}
  DEFAULT_TAG: latest

jobs:
  prebuild-self:
    name: Prebuild own Dev Container
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Prebuild Environment
        id: setup
        uses: ./
        with:
          platforms: ${{ inputs.platforms || env.DEFAULT_PLATFORMS }}

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry || env.DEFAULT_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prebuild and publish image
        uses: devcontainers/ci@v0.3
        env:
          REGISTRY: ${{ inputs.registry || env.DEFAULT_REGISTRY }}
          REPOSITORY: ${{ inputs.repository || env.DEFAULT_REPOSITORY }}
          TAG: ${{ inputs.tag || env.DEFAULT_TAG }}
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          imageTag: ${{ env.TAG }}
          configFile: .devcontainer/source/devcontainer.json
          refFilterForPush: |
            refs/heads/main
          eventFilterForPush: |
            push
            workflow_dispatch
          platform: ${{ steps.setup.outputs.platforms }}
