name: Lint
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  constants:
    name: Check Golang Platform Constants
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check KNOWN_ARCH
        run: ./src/golang.sh KNOWN_ARCH

      - name: Check KNOWN_OS
        run: ./src/golang.sh KNOWN_OS

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s sh -P src
