name: (Custom) Prebuild Dev Container
on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: string
        description: Workflow runner machine type
        required: false
        default: ubuntu-latest
      platforms:
        type: string
        description: Comma-separated OCI build platforms
        required: false
        default: linux/amd64,linux/arm64
      registry:
        type: string
        description: Container registry server
        required: false
        default: ghcr.io
      username:
        type: string
        description: Container registry username
        required: false
      repository:
        type: string
        description: Registry repository name
        required: false
      tag:
        type: string
        description: Container image tag
        required: false
        default: latest
      push:
        type: boolean
        description: Push the image to the registry
        required: false
        default: true
      cache:
        type: boolean
        description: Cache downloaded dependencies
        required: false
        default: true

env:
  CACHE: ${{ inputs.cache && 'true' || 'false' }}
  PASSWORD: ${{ secrets.PREBUILD_PASSWORD || secrets.GITHUB_TOKEN }}
  PLATFORMS: ${{ inputs.platforms || vars.PREBUILD_PLATFORMS || 'linux/amd64,linux/arm64' }}
  PUSH: ${{ inputs.push && 'always' || 'never' }}
  REGISTRY: ${{ inputs.registry || vars.PREBUILD_REGISTRY || 'ghcr.io' }}
  REPOSITORY: ${{ inputs.repository || vars.PREBUILD_REPOSITORY || github.repository }}
  TAG: ${{ inputs.tag || vars.PREBUILD_TAG || 'latest' }}
  USERNAME: ${{ inputs.username || vars.PREBUILD_USERNAME || github.actor }}

jobs:
  custom-prebuild:
    name: Prebuild own Dev Container
    runs-on: ${{ inputs.runs-on || vars.PREBUILD_RUNS_ON || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Prebuild Environment
        id: setup
        uses: ./
        with:
          cache: ${{ env.CACHE }}
          password: ${{ env.PASSWORD }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}

      - name: Prebuild and publish image
        uses: devcontainers/ci@v0.3
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ env.REPOSITORY }}
          TAG: ${{ env.TAG }}
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          imageTag: ${{ env.TAG }}
          push: ${{ env.PUSH }}
          platform: ${{ steps.setup.outputs.platforms }}
