name: (Custom) Prebuild Dev Container
on:
  workflow_dispatch:
    inputs:
      platforms:
        description: Comma-separated list of OCI platforms to build for
        required: false
      push:
        description: Whether to push the image to the registry
        required: false
        default: 'true'
      registry:
        description: Container registry to publish to
        required: false
        default: ghcr.io
      repository:
        description: Image repository to publish to
        required: false
      runs-on:
        description: Type of machine to run the workflow on
        required: false
        default: ubuntu-latest
      tag:
        description: Container image tag to publish with
        required: false
        default: latest

env:
  PASSWORD: ${{ secrets.PREBUILD_PASSWORD || secrets.GITHUB_TOKEN }}
  PLATFORMS: ${{ inputs.platforms || vars.PREBUILD_PLATFORMS || 'linux/amd64,linux/arm64' }}
  PUSH: ${{ inputs.push == 'true' && 'always' || 'never' }}
  REGISTRY: ${{ inputs.registry || vars.PREBUILD_REGISTRY || 'ghcr.io' }}
  REPOSITORY: ${{ inputs.repository || vars.PREBUILD_REPOSITORY || github.repository }}
  TAG: ${{ inputs.tag || vars.PREBUILD_TAG || 'latest' }}
  USERNAME: ${{ inputs.username || vars.PREBUILD_USERNAME || github.repository_owner }}

jobs:
  custom-prebuild:
    name: Prebuild own Dev Container
    runs-on: ${{ inputs.runs-on || vars.PREBUILD_RUNS_ON || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Prebuild Environment
        id: setup
        uses: ./
        with:
          password: ${{ env.PASSWORD }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}

      - name: Prebuild and publish image
        uses: devcontainers/ci@v0.3
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ env.REPOSITORY }}
          TAG: ${{ env.TAG }}
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          imageTag: ${{ env.TAG }}
          configFile: .devcontainer/source/devcontainer.json
          push: ${{ env.PUSH }}
          platform: ${{ steps.setup.outputs.platforms }}
